### ISSUE TITLE
Compilation Error in SEGGER Embedded Studio for Wio-WM1110 Dev Kit

### ISSUE THREAD

**Issue by Unaitecnalia** [Seeed-Studio/Seeed_Wio_WM1110_Dev_Board#1]
# Compilation Error with Wio-WM1110 Dev Kit in SEGGER Embedded Studio

Hello,

I'm encountering some compilation issues while working on a project with the [Wio-WM1110 Dev Kit](https://wiki.seeedstudio.com/Wio-WM1110_Dev_Kit_Hardware_Overview/) using SEGGER Embedded Studio v7.32. I have imported several header files, including `nrf.h`, `nrfx.h`, `compiler_abstraction.h`, `nrf52840.h`, `nrf_drv_clock.h`, `nrf_drv_uart.h`, `nrf_config.h`, `nrfx_config.h`, `system_nrf52840.h`, `nrf_storage.h`, and `nrf_uart.h`.

However, when I attempt to compile the project, I am getting the following error:

```plaintext
Building ‘wm1110_dev_kit_pca10056’ from solution ‘wm1110_dev_kit_pca10056’ in configuration ‘Debug’
  Compiling ‘app_uart_fifo.c’
  Compiling ‘nrf_fstorage_nvmc.c’
  Compiling ‘nrf_pwr_mgmt.c’
  Compiling ‘nrf_section_iter.c’
  Compiling ‘nrf_strerror.c’
  Compiling ‘nrf_drv_clock.c’
    nrf_drv_clock.h
    nrf_drv_clock.c
    #error "This code is not supposed to be compiled when neither POWER nor CLOCK is enabled."
    expected expression before ')' token
    unknown type name 'ret_code_t'
    unknown type name 'ret_code_t'
    unknown type name 'ret_code_t'
    unknown type name 'ret_code_t'
    incompatible type for argument 1 of 'nrf_clock_task_address_get'
    expected 'const NRF_CLOCK_Type *' but argument is of type 'nrf_clock_task_t'
    too few arguments to function 'nrf_clock_task_address_get'
    declared here
    incompatible type for argument 1 of 'nrf_clock_event_address_get'
    expected 'const NRF_CLOCK_Type *' but argument is of type 'nrf_clock_event_t'
    too few arguments to function 'nrf_clock_event_address_get'
    declared here
  Compiling ‘nrf_drv_rng.c’
  Compiling ‘nrf_drv_uart.c’
    nrf_drv_uart.c
    unknown type name 'nrf_uarte_baudrate_t'
    unknown type name 'nrf_uarte_error_mask_t'
    unknown type name 'nrf_uarte_hwfc_t'
    unknown type name 'nrf_uarte_parity_t'
    unknown type name 'nrf_uarte_task_t'
    unknown type name 'nrf_uarte_event_t'
    unknown type name 'ret_code_t'
    unknown type name 'ret_code_t'
    unknown type name 'ret_code_t'
    unknown type name 'ret_code_t'
    unknown type name 'ret_code_t'
    unknown type name 'ret_code_t'
    unknown type name 'ret_code_t'
    Build failed
  Compiling ‘nrf_nvmc.c’
  Compiling ‘nrf_nvic.c’
  Compiling ‘nrfx_atomic.c’
  Compiling ‘nrfx_clock.c’
Build failed
```

The error message doesn't specify which header file is causing the issue; it simply mentions "unknown type names."

I would appreciate any help identifying the error's cause and guidance on resolving it, including suggestions on missing header files or potential solutions.

Thank you in advance for your assistance!

**Comment by Jessie219-web** [comment]
Hi，
thanks.
which project do you compile? could you take a screenshot of the explorer? 
please contact sensecap@seeed.cc for more details.
<img width="449" alt="企业微信截图_16971694079024" src="https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/112080869/63dce3dd-06ff-424b-953a-3316e9b90c00">

**Comment by unaiberis** [comment]
Hi Jessie,

I am working on this project and trying to compile it.

![image](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146723346/02b2f765-fa4e-4714-ad49-1a5aee737e41)

Thanks

**Comment by Unaitecnalia** [comment]
## Issue: Resolving Compilation and Linker Errors in Seeed Wio WM1110 Dev Board Project

### Description

Hi Jessie, I encountered a series of errors while working on the Seeed Wio WM1110 Dev Board project, which I was able to resolve through a series of steps. I'd like to share my experiences and solutions here for reference and to help others facing similar issues.

### Issue Resolution

#### Step 1: Incorrect Nordic SDK Path

- The project was searching for the Nordic SDK in a path six folders above the project root (`../../../../../../`). This left the path of this GitHub project and searched for it in some other folders on my PC, in my case, it was searching in the Users folder.

  ![Incorrect Nordic SDK Path](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146721756/7c951c12-6392-4d28-b888-64694d4df1d0)

- To solve this problem, I created subfolders to make the links search in my project folder and copied the SDK into that folder. I had to install NRF SDK 17.10 and NRF SDK 15.3.0 (reduced master) to resolve SDK-related problems.

  ![Updated Folder Structure](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146721756/38ad97f6-ec35-4a29-93e5-896c610fae7f)
  ![Updated Folder Structure](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146721756/42c5cf73-ef1f-4124-a24a-3e679b785c60)
  ![Updated Folder Structure](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146721756/14be17e4-7043-4227-aada-d7187fbbc887)

#### Step 2: Library I/O Configuration

- I resolved the following errors related to Library I/O configuration:

   - `7.32/lib/libc_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a(fileops.o): in function 'putchar'`
   - `7.32/lib/libc_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a(fileops.o): in function 'puts'`
   - `7.32/lib/libc_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a(fileops.o): in function 'fwrite'`

   These errors were resolved by changing the Library I/O from "None" to "RTT," as explained in this [DevZone post](https://devzone.nordicsemi.com/f/nordic-q-a/87492/uart-example-in-nrf5-sdk-v17-0-2-not-working-as-expected-when-built-using-segger-embedded-studio-for-arm-v6-22).

  ![Library I/O Configuration](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146721756/7c17f6cb-9ebf-41fa-88bb-758e24138ef6)

#### Step 3: ".text" and ".rodata" Size Errors

- I encountered ".text is larger than specified size" and ".rodata is larger than specified size" errors and fixed them by referring to this [DevZone post](https://devzone.nordicsemi.com/f/nordic-q-a/89236/build-error/374975).

  ![Size Specification](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146721756/b2f94402-6fcc-48e5-97b5-88ab54dbdc14)

#### Step 4: "undefined reference to `__RAM_segment_end__`" Error

- I resolved this error by changing them from RAM1 to RAM, which is the reverse of what the [DevZone post](https://devzone.nordicsemi.com/f/nordic-q-a/66297/linker-error-when-upgrading-to-sdk-17-0-from-15-2) suggests.

  ![RAM Configuration](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146721756/3122a352-50b1-49f3-a25f-6d6dc0ed2c37)
  ![RAM Configuration](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146721756/7cf4a9c4-138f-4572-bde8-94966c9d765b)

#### Correct Compilation

- Finally, after implementing the above changes, the compilation was successful without errors.

  ![Correct Compilation](https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/assets/146721756/7cf4a9c4-138f-4572-bde8-94966c9d765b)

**Comment by WayenWeng** [comment]
@Unaitecnalia Thanks for your feedback. There is a simpler way here, refer to this: https://wiki.seeedstudio.com/Get_Started_with_Wio-WM1110_Dev_Kit/#running-a-first-test
![image](https://github.com/user-attachments/assets/61b475e3-349b-40dd-ad4e-49b057daea34)
Can you try it?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
