### ISSUE TITLE
Build Error in segger Embedded Studio

### ISSUE THREAD

**Issue by yashkathe** [Seeed-Studio/Seeed_Wio_WM1110_Dev_Board#3]
I am using segger embedded studio to flash code via usb ch340c.
I was going to build the project then flash the hex file using nrf connect.

But I am getting the following error when building blinky project
![image](https://github.com/user-attachments/assets/74267ac0-368d-4451-bcfc-4bfcb5353463)

I could't find any guide for flashing code in wio dev board using usb.
Is there any proper documentation atleast to get started with the board?

**Comment by WayenWeng** [comment]
@yashkathe There is building path error. Please refer to this: 
https://wiki.seeedstudio.com/Get_Started_with_Wio-WM1110_Dev_Kit/#running-a-first-test
![image](https://github.com/user-attachments/assets/a2f1c405-132a-4cef-a27f-636ea4749a18)

**Comment by yashkathe** [comment]
Thank you so much I was able to run the program
