### ISSUE TITLE
GNSS Antenna port number 

### ISSUE THREAD

**Issue by yashkathe** [Seeed-Studio/Seeed_Wio_WM1110_Dev_Board#4]
The dev board has 2 connectors on it U.FL and other the bigger one. So my doubt is do we have to mention it somewhere on which port  the GNSS antenna is connected ?

Also, can we reduce the number of satellites the GNSS antenna has to connect to before sending GPS payload? Because the process takes time to start the GNSS middleware and even after that. Are there any docs to the API where I can read more ?

My GNSS antenna works perfectly for bigger connector
but for u.fl connector I keep getting error: 

![image](https://github.com/user-attachments/assets/a5dce733-e5a9-42c4-afe3-ba247b8077b4)

The following error says indoor_Detected 1 but the other antenna works fine in the same environmental setting

**Comment by Lesords** [comment]
@WayenWeng help with this one.
