### ISSUE TITLE
setting assist_position for GNSS antennas

### ISSUE THREAD

**Issue by yashkathe** [Seeed-Studio/Seeed_Wio_WM1110_Dev_Board#5]
Where can I set the assist_position for GNSS antennas?

While testing the GNSS antennas I noticed it uses a pre-defined set of coordinates for assist_position. I question I have is where is this assist_position set? Right now I am testing this in the US and the assist positions that the logs show point to coordinates in China. Just for additional context I am using the Things Network for the Network server.

![Screenshot 2024-11-10 213306](https://github.com/user-attachments/assets/ac4626c9-f648-4bb9-b9be-1338a40719eb)

**Comment by Lesords** [comment]
@WayenWeng Help with this one.

**Comment by WayenWeng** [comment]
@yashkathe You can change the assist position such as follow:
https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/blob/master/apps/examples/geolocation_gnss/main_geolocation_gnss.h#L67
https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/blob/master/apps/examples/geolocation_gnss_wifi/main_geolocation_gnss_wifi.h#L67

**Comment by yashkathe** [comment]
Thank you so much!!

**Comment by yashkathe** [comment]
Thank you so much!!
